//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartProIK.Models.db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IKDBEntities1 : DbContext
    {
        public IKDBEntities1()
            : base("name=IKDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adresler> Adresler { get; set; }
        public virtual DbSet<Diller> Diller { get; set; }
        public virtual DbSet<EgitimBilgileri> EgitimBilgileri { get; set; }
        public virtual DbSet<Emailler> Emailler { get; set; }
        public virtual DbSet<Kullanicilar> Kullanicilar { get; set; }
        public virtual DbSet<Onyazilar> Onyazilar { get; set; }
        public virtual DbSet<Sertifikalar> Sertifikalar { get; set; }
        public virtual DbSet<Tecrubeler> Tecrubeler { get; set; }
        public virtual DbSet<Yetenekler> Yetenekler { get; set; }
    }
}
