//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartProIK.Models.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sertifikalar
    {
        public int id { get; set; }
        public string ad { get; set; }
        public string kurum { get; set; }
        public string brans { get; set; }
        public System.DateTime yil { get; set; }
        public int sure { get; set; }
        public string aciklama { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
    }
}
